#config.yaml

#data loader parameters
batch_size: 8
shuffle: True
num_workers: 4

#unet parameters
input_size: [3,512,512]  # (channels, height, width)
initial_filters: 64
depth: 3
learning_rate: 0.001
epochs: 20
device: "cuda"